src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity(fields: ['email'], message: "Il'y a déjà un compte, qui corresponde à cet email")]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 5)]
    private ?string $zipcode = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(type: 'datetime_immutable', options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\OneToMany(mappedBy: 'users', targetEntity: Orders::class)]
    private Collection $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        // on ajout la creation de date automatique ,immutable ne change pas la date d'objet , seulement sa copie
        $this->created_at = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Orders>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders->add($order);
            $order->setUsers($this);
        }

        return $this;
    }

    public function removeOrder(Orders $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUsers() === $this) {
                $order->setUsers(null);
            }
        }

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Entity\Orders;
use App\Entity\OrdersDetails;
use App\Entity\Products;
use App\Repository\OrdersDetailsRepository;
use App\Repository\OrdersRepository;
use App\Repository\ProductsRepository;
use App\Service\Cart\CartService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class CartController extends AbstractController
{
    #[Route('/cart', name: 'cart')]    // j'ai renomé la route pour "cart"
    public function index(CartService $cartService): Response
    {

        $panierDonnees = $cartService->getFullCart();

        $total = $cartService->getTotal();
        

        return $this->render('cart/cart.html.twig', [
            'items' => $panierDonnees,   //on envoie les données au twig
            'total'  => $total
        ]);
    }
     
    // ajouter le produit dans le panier
    #[Route('cart/add/{id}', name: 'cart_add')]
    public function add($id, CartService $cartService)
    {

        $cartService->add($id);
        
        // pour cette function on fait redirecToRoute et NON render !!
        return $this->redirectToRoute('cart', []);
    }

    // reduir le quantité de produit selectionné
    #[Route('cart/enlever/{id}', name: 'cart_enlever')]
    public function enlever(Products $products, CartService $cartService)
    {

        $cartService->enlever($products);

        return $this->redirectToRoute('cart');

    }


    //supression d'un produit de panier

    #[Route('cart/remove/{id}', name: 'cart_remove')]
    public function remove($id, CartService $cartService)
    {
        $cartService->remove($id);


        return $this->redirectToRoute('cart');

    }

    // supression de panier total
    #[Route('cart/delete', name: 'delete')]
    public function deleteAll(SessionInterface $session)
    {
        $session->remove('panier');

        return $this->redirectToRoute('cart');

    }


    // validation de commande : je recuper les classes cartservices, Orders, OrdersDetails ,
    // EntityManagerInterface => tout ceux que nous avons besoins pour enregistrer la commande=order
    #[Route('cart/commande', name: 'commande')]
    public function validationCommande( ProductsRepository $repoProduit, SessionInterface $session, CartService $cartService, EntityManagerInterface $maneger, Orders $order = null, OrdersDetails $orderDetails = null, ): Response
    { 
        $order = new Orders;   
        // pour recupere utilisateur, on utilise la methode de symfony getUser() d'AbstractController.php  
        $order->setUsers($this->getUser());
        $order->setMontant($cartService->getTotal());
        // dd($order); 
        $maneger->persist($order);
        $maneger->flush(); // on enregister la commande

        // dd($order);
        // ___________________________________________________

        // creation de OrdersDetails
        // ___________________________________________________
        //on recupere le panier via $session;
        $panier = $session->get('panier');

        // on declare le tableau de donées de panier
        $panierDonnees = [];

        foreach($panier as $key => $value)
        {
            $panierDonnees[] = [
                'products' => $repoProduit->find($key),
                'quantity' => $value
            ];
        }

        //   dd($panierDonnees);

        foreach($panierDonnees as $key => $value)
        {
            // on declare variable $orderDetails pour y enregestrer les données
            $orderDetails = new OrdersDetails;

            //on recuper $id de produit de données de panier
            $id = $value['products']->getId();
            
            // on recupere l'objet "products"
            $products = $repoProduit->find($id);

            // on recuper stock de produit pour faire mis à jour 
            $stock = $products->getStock();

            // on rensegne setteur de $orderDetails 
            $orderDetails->setOrders($order);
            $orderDetails->setQuantity($value['quantity']);
            $orderDetails->setPrice($value['products']->getPrice());
            $orderDetails->setProducts($products);


            // on prepare données de orderDetails pour enregestrer
            $maneger->persist($orderDetails);
            
            // on reduit le stock de produit
            $products->setStock($stock - $value['quantity']);
            
            // on prepare enregistrer le changement de stock
            $maneger->persist($products);

        }
        // on enregister données
        $maneger->flush();

        // dd($orderDetails);
        // mis à jour stock dans BDD


        // on supprime le panier apres enregistrement de commande
        $session->remove('panier');

        return $this->render('cart/commande.html.twig', [
            'order' => $order,
            'details' => $orderDetails
        ]);
    }

    // affichage de détails de commande
    #[Route('/cart_details/{id}', name: 'cart_details', methods: ['GET'])]
    public function detailsCommande($id, OrdersDetailsRepository $detailsRepo, OrdersRepository $orderRepo)
    {
        $order = $orderRepo->find($id);
        $orders_id = $id;
        $details = $detailsRepo->findByOrders($orders_id);

        // dd($details);

        return $this->render('cart/cart_details.html.twig', [
            'details' => $details,
            'order' => $order
        ]);
    }







}

templates/cart/cart.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}

<div class="container panier">

{% if items | length > 0 %}

    <h2 class="text-center my-5">Votre Panier</h1>

    {#  on présente nos produits dans un tableau#}

<div class="col-lg-6 col-md-10 mx-auto">
    <table class="table border shadow text-center mb-5">
        <tr>
            <th>Nom de produit</th>
            <th>Prix</th>
            <th>Quantité</th>
            <th>Total</th>
            <th>Actions</th>
        </tr>
        {% for item in items %}
        <tr>
            <td>{{ item.product.name}}</td>
            <td>{{ item.product.price}}DT</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.product.price * item.quantity}}DT</td>
            <td>
                <a href="{{ path('cart_add', {id: item.product.id})}}" class="btn btn">
                            <i class="bi bi-plus-lg"></i>
                        </a>
                        <a href="{{ path('cart_enlever', {id: item.product.id})}}" class="btn btn">
                            <i class="bi bi-dash-lg"></i>
                        </a>
                <a href="{{ path('cart_remove', {'id': item.product.id})}}" class="btn btn"><i class="bi bi-trash3"></i></a>
            </td>
        </tr>    
        {% endfor %}
        <tfoot>
            <tr>
                <td class="text-end" colspan="3">Montant total :</td>
                <td>{{ total }} DT</td>
                <td>
                    <a href="{{ path('delete')}}" class="btn btn-danger">
                        <i class="bi bi-cart-x"></i>
                    </a>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
<div class="d-flex flex-wrap justify-content-around my-5">
    <a href="{{ path('produits')}}" class="btn_continuer my-2">Continuer les achats <i class="bi bi-arrow-right"></i></a>
            
        {% if not app.user %}
        <div class="d-flex justify-content-around btn_cart">
            <a class="btn_continuer" href="{{ path('app_login')}}">Pour valider : connectez-vous</a>
            <p class="mx-3">ou</p>  
            <a class="btn_continuer" href="{{ path('app_register')}}">Inscrivez-vous</a> 
        </div>
        {% else %}
            <a href="{{ path('commande')}}" class="btn_valider my-2">Validez votre commande !</a>

        {% endif %}
</div>       
{% else %}

        <h3 class="text-center position-absolute top-50 start-50 translate-middle">Votre panier est vide !</h3>
        
{% endif %}
</div>
{% endblock %}

templates/cart/cart_details.html.twig
{% extends 'base.html.twig' %}

    {% block title %}
        Détails de commande    
    {% endblock %}

{% block body %}
<div class="container detailsOrder">
    <h4 class="my-5">Détails de votre commande N° {{ order.id}}<p class="fst-italic fw-ligth mt-2">faite le {{ order.createdAt|date('d/m/Y  à H:i', 'Europe/Paris')}}</p></h4>

    <div class="col-lg-6 col-md-10 mx-auto mb-5"> 
        <table class="table text-center">
            <tr>
                <th>Nom</th>
                <th></th>
                <th>Prix</th>
                <th>Quantité</th>
                <th>Total</th>
            </tr>    
            {% for detail in details %}
            <tr>
                <td>{{ detail.products.name}}</td>
                <td><img src="{{ asset('uploads/images/produits/' ~ detail.products.image) }}" width="50" alt="{{ detail.products.name }}"></td>
                <td>{{ detail.price }}€</td>
                <td>{{ detail.quantity }}</td>
                <td>{{ detail.price * detail.quantity }}DT</td>
            </tr>
            {% endfor %}
            <tfoot>
                <td class="text-end" colspan="4">Montant total :</td>
                <td><h5>{{ order.montant }} DT</h5></td>
            </tfoot>  
        </table>
    </div>
</div>   


{% endblock %}

templates/cart/commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}

{% block body %}
<div class="container panier">

<h3 class="text-center my-5">Bonjour {{ app.user.firstname }} {{ app.user.lastname}}</h3>
<h3 class="text-center">Votre commande N° {{ order.id }} pour un montant {{ order.montant }} DT</h3>
        <h3 class="text-center my-5">Merci pour votre confiance !</h3>
        <p class="text-center"><a href="{{ path('cart_details', {'id' : order.id})}}">Voir les détails -></a></p>

</div>
{% endblock %}